# CONCENTRATION
concentration: 0.15
num_particles: 500

# SIMULATION SETTINGS
equil_steps: 100
prod_steps: 50000
output_interval: 100
internal_interval: 1000
seed: 11

# BIAS SETTINGS
bias_type: linear
max_target: 50
bias_file: bias/150mM_implicit_50mer.txt

# MOVE RATES
avbmc_rate: 0.2
nvt_rate: 0.1
translation_rate: 0.7
swap_rate: 0.0
max_displacement: 30

# CLUSTER DEFINITION
upper_bonded_cutoff: 3.5
lower_bonded_cutoff: 2.5
clust_cutoff: 3.5

# INPUT FILES
model_path: /gscratch/cheme/mzorman/06_MLP/models/NaCl/NaCl_0518_1r.nequip.pth
input_path: null
